AWSTemplateFormatVersion: '2010-09-09'

Description: Setup a DNS Zone with CAA and Office365 records

Parameters:
    DomainName: 
      Type: String
      Description: Enter a new domain to configure

    DomainKey:
      Type: String
      Description: Your domain-key from the Office365 portal
      Default: domain-com
      
Resources:
  DNSZone:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/oramco-cfn/oramco/cfn-dns-zone/cfn-dns-zone.yaml
      Parameters:
        DomainName: !Ref DomainName
      TimeoutInMinutes: '60'

  DNSCAARecords:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/oramco-cfn/oramco/cfn-dns-caa/cfn-dns-caa.yaml
      Parameters:
        DomainName: !Ref DomainName
        ZoneId: !GetAtt DNSZone.Outputs.ZoneId
      TimeoutInMinutes: '60'

  DNSOffice365:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/oramco-cfn/oramco/cfn-dns-office365/cfn-dns-office365.yaml
      Parameters:
        DomainName: !Ref DomainName
        ZoneId: !GetAtt DNSZone.Outputs.ZoneId
        DomainKey: !Ref DomainKey
      TimeoutInMinutes: '60'
